config/routes.rb
Rails.application.routes.draw do
  scope "auth" do
    get "/" => "auth#index"
    get "callback" => "auth#callback"
    get "logout" => "auth#logout"
  end
  scope "admin" do
    get "/" => "admin#index"
    get "console" => "admin#console"
  end
  resources :set_scores, only: [:index, :update]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root "home#index"
  get "results" => "scoreboard#results"
  get "scoreboard" => "scoreboard#index"
end

app/models/set_score.rb
class SetScore < ApplicationRecord
end

app/controllers/set_scores_controller.rb
class SetScoresController < ApplicationController
  include UserRoles
  before_action :authorize_scorer
  skip_before_action :verify_authenticity_token if Rails.env.development?
  def index
    if (params[:year].nil? and params[:activity].nil?)
      @events = Event.order("id ASC")
    elsif (params[:year].nil? )
      @events = Event.where(activity: params[:activity]).order("id ASC")
    else
      @events = Event.where(year: params[:year]).order("id ASC")
    end
    @activities = Event.where(year: 9, gender: "Boys").or(Event.where(year: 9, gender: "Mixed")).order("id ASC") # This could use any year and gender, I just went for Y9 & boy because it's the fewest characters
  end

  def update
    event = Event.find_by(id: params[:id])
    event.update(sharman: params[:sharman], winston: params[:winston], ennis: params[:ennis], turing: params[:turing])
    #flash.alert = "Updated data for the #{event.year} #{event.gender} #{event.activity} event"
  end
end

app/helpers/set_scores_helper.rb
module SetScoresHelper
    def render_dropdowns(id, form, value)
        options = [
            add_option_tag("1", 20, value),
            add_option_tag("2", 15, value),
            add_option_tag("3", 10, value),
            add_option_tag("4", 5, value),
            add_option_tag("Nothing", 0, value)
        ]
    content_tag(:select, options.join.html_safe, name: form, id: id)
    end

    private
    def add_option_tag(name, value, dataToCheckAgainst)
        if value == dataToCheckAgainst
            content_tag(:option, name, value: value, selected: true)
        else
            content_tag(:option, name, value: value)
        end
    end
end

app/views/set_scores/index.html.erb
<%= render "buttons" %>

<a href="/set_scores">All</a>
<a href="/set_scores?year=9">Year 9</a>
<a href="/set_scores?year=10">Year 10</a>
<a href="/set_scores?year=11">Year 11</a>
<br/>
<% flash.each do |type, msg| %>
  <div class="message">
    <%= msg %>
  </div>
<% end %>
<div class='settable'>
<table border=1>
  <tr>
    <th>Activity</th>
    <th>Year</th>
    <th>Group</th>
    <th class="winston">Winston</th>
    <th class="ennis">Ennis</th>
    <th class="sharman">Sharman</th>
    <th class="turing">Turing</th>
    <th>Change Score</th>
  </tr>
  <% @events.each do |event| %>
    <%= turbo_stream_from event %>
    <tr>
      <%= form_with url: set_score_path(id: event.id), method: :put, remote: true do |form| %>
        <td><%= event.activity %></td>
        <td><%= event.year %></td>
        <td><%= event.gender %></td>
        <td class="winston"><%= render_dropdowns("#{event.id}-winston", "winston", event.winston) %></td>
        <td class="ennis"><%= render_dropdowns("#{event.id}-ennis", "ennis", event.ennis) %></td>
        <td class="sharman"><%= render_dropdowns("#{event.id}-sharman", "sharman", event.sharman) %></td>
        <td class="turing"><%= render_dropdowns("#{event.id}-turing", "turing", event.turing) %></td>
        <td class="setscorebutt"><%= form.submit "Set Score" %></td>
      <% end %>
    </tr>
  <% end %>
</table>    
</div>

<% @activities.each do |activity| %>
  <%= link_to activity.activity, set_scores_path(:activity => activity.activity) %>
<% end %>